import type { FileItem } from "@/types/file-system"

export const mockFileSystem: Record<string, FileItem[]> = {
  "/": [
    {
      id: "1",
      name: "Documents",
      type: "folder",
      modifiedAt: new Date("2024-01-15"),
      owner: "me",
    },
    {
      id: "2",
      name: "Photos",
      type: "folder",
      modifiedAt: new Date("2024-01-10"),
      owner: "me",
    },
    {
      id: "3",
      name: "Projects",
      type: "folder",
      modifiedAt: new Date("2024-01-20"),
      owner: "me",
    },
    {
      id: "4",
      name: "Resume.pdf",
      type: "file",
      size: 245760,
      modifiedAt: new Date("2024-01-12"),
      owner: "me",
      url: "/resume-document.png",
    },
    {
      id: "5",
      name: "Budget_2024.xlsx",
      type: "file",
      size: 51200,
      modifiedAt: new Date("2024-01-08"),
      owner: "me",
      url: "/spreadsheet-budget.png",
    },
  ],
  "/Documents": [
    {
      id: "6",
      name: "Meeting Notes",
      type: "folder",
      modifiedAt: new Date("2024-01-14"),
      owner: "me",
    },
    {
      id: "7",
      name: "Contracts",
      type: "folder",
      modifiedAt: new Date("2024-01-11"),
      owner: "me",
    },
    {
      id: "8",
      name: "Project_Proposal.docx",
      type: "file",
      size: 102400,
      modifiedAt: new Date("2024-01-13"),
      owner: "me",
      url: "/document-proposal.jpg",
    },
    {
      id: "9",
      name: "Research_Notes.txt",
      type: "file",
      size: 8192,
      modifiedAt: new Date("2024-01-09"),
      owner: "me",
      url: "/text-notes.jpg",
    },
  ],
  "/Photos": [
    {
      id: "10",
      name: "Vacation_2023.jpg",
      type: "file",
      size: 2048000,
      modifiedAt: new Date("2023-12-25"),
      owner: "me",
      url: "/vacation-beach-photo.jpg",
    },
    {
      id: "11",
      name: "Family_Portrait.png",
      type: "file",
      size: 1536000,
      modifiedAt: new Date("2024-01-01"),
      owner: "me",
      url: "/diverse-family-portrait.png",
    },
    {
      id: "12",
      name: "Screenshots",
      type: "folder",
      modifiedAt: new Date("2024-01-05"),
      owner: "me",
    },
  ],
  "/Projects": [
    {
      id: "13",
      name: "Website_Redesign",
      type: "folder",
      modifiedAt: new Date("2024-01-18"),
      owner: "me",
    },
    {
      id: "14",
      name: "Mobile_App",
      type: "folder",
      modifiedAt: new Date("2024-01-16"),
      owner: "me",
    },
    {
      id: "15",
      name: "presentation.pptx",
      type: "file",
      size: 5120000,
      modifiedAt: new Date("2024-01-19"),
      owner: "me",
      url: "/business-presentation.png",
    },
  ],
  "/Documents/Meeting Notes": [
    {
      id: "16",
      name: "Q1_Planning.docx",
      type: "file",
      size: 76800,
      modifiedAt: new Date("2024-01-14"),
      owner: "me",
      url: "/meeting-notes-document.jpg",
    },
    {
      id: "17",
      name: "Team_Standup_Jan.txt",
      type: "file",
      size: 4096,
      modifiedAt: new Date("2024-01-12"),
      owner: "me",
      url: "/standup-notes.jpg",
    },
  ],
  "/Photos/Screenshots": [
    {
      id: "18",
      name: "Dashboard_Design.png",
      type: "file",
      size: 512000,
      modifiedAt: new Date("2024-01-05"),
      owner: "me",
      url: "/dashboard-ui-design.jpg",
    },
    {
      id: "19",
      name: "Error_Message.jpg",
      type: "file",
      size: 256000,
      modifiedAt: new Date("2024-01-03"),
      owner: "me",
      url: "/error-message-screenshot.png",
    },
  ],
}
